---
title: "Data exploration"
output: html_document
---

```{r setup, include=FALSE}

library(gsheet)
library(tidyverse)
library(brms)
library(tidybayes)
library(ape)
library(tidytree)
library(ggthemes)
library(tidyboot)
library(readxl)

```

# Download data files

```{r}

# The following only needs to be run when the data is updated. Skip to next snippet if ther is no update

#folder link to id
jp_folder = "https://drive.google.com/drive/folders/1YRzkqJxZzfhUE0k5bxHI1Sxnu4lLsWTV"
folder_id = drive_get(as_id(jp_folder))

#find files in folder
files <-  drive_ls(as_id(folder_id), type = "folder")

# object to store all file names 
all_files <- tibble()

#loop dirs and list files inside them
for (i in seq_along(files$name)) {
  #list files
  i_dir = drive_ls(files[i, ])
  
  all_files <- bind_rows(all_files, i_dir)
  
   
}

# filter out all datasheets
data_files <- all_files%>%
  filter(grepl("datasheet", name))

# download all datasheets

  for (file_i in seq_along(data_files$name)) {
    #fails if already exists
    try({
      drive_download(
        as_id(data_files$id[file_i]),
        path = str_c("../data/", data_files$name[file_i], data_files$id[file_i])
      )
    })
  }


```

# Load and clean data files

## Accumulation task

### Leipzig

```{r}
acc_leip <- read_xlsx("../data/Many_Primates_mp2_accumulation_datasheet_leipzig1_0E-r8MU6_48JTdKM9X0f70ZddqIhCiFQJe4eX2kBoY.xlsx", sheet = 2)%>%
  mutate(testing_time = substr(as.character(testing_time),12,16),
         date = as.character(date)) # fix dates later
```

### Edinburgh

```{r}
acc_edin <- read_xlsx("../data/Many_Primates_mp2_accumulation_datasheet_EdinBRU10CAVQp2NMfRwZ8vyFZNUiODqWMLzjTvNpUof74x0B40.xlsx", sheet = 2)%>%
  mutate(testing_time = substr(as.character(testing_time),12,16),
         date = as.character(date)) # fix dates later)
```

### Strasbourg

```{r}
acc_stras <- read_xlsx("../data/Many_Primates_mp2_accumulation_datasheet_template129zgrLvXIo8M80Ikyx9c57SzEqeptVuptx0U8kw_j1M.xlsx", sheet = 2)%>%
  mutate(testing_time = substr(as.character(testing_time),12,16),
         date = as.character(date),
         food_amount = as.character(food_amount)) # fix dates later)
```

### Kristiansand

```{r}
# had to download this data file manually becasue it was in a subfolder 
acc_kris <- read_xlsx("../data/Many_Primates_mp2_KRI_accumulation_datasheet_template.xlsx", sheet = 2)%>%
  mutate(testing_time = substr(as.character(testing_time),12,16),
         date = as.character(date),
         food_amount = as.character(food_amount)) # fix dates later)
```


### Merge

```{r}
acc_data <- bind_rows(
  acc_leip,
  acc_edin,
  acc_stras,
  acc_kris
)%>%
  mutate(species = tolower(species), 
         species = str_replace_all(species," ", "_"),
         species = recode(species, 
                          'sumatran_orangutan' = 'orangutan',
                          'macaca_tonkeana' = 'tonkean_macaque',
                          'macaca_fascicularis' = 'long_tailed_macaque',
                          'buff_cheek_gibbon/white_cheek_gibbon_hybrid' = 'buff_cheek_gibbon',
                          'whitefaced_saki' = 'white_faced_saki',
                          "bornean_orangutan" = "orangutan"
                          ),
         inter_item_interval = ifelse(inter_item_interval == 16, 12, inter_item_interval), # The Strasbourg data has 2,4,8 and 16s as conditions, not 12s as the longest like everyone else. We need to check back with them to make that it was actually 12s. 
         clade = recode(species, 
                        "gorilla" = "Hominoidea",
                        "chimpanzee"= "Hominoidea",
                        "patas_monkey" = "Cercopithecoidea",
                        "bonobo"      = "Hominoidea",        
                        "orangutan"   = "Hominoidea",       
                        "hamlyns_monkey" = "Cercopithecoidea",
                        "diana_monkey"   = "Cercopithecoidea",   
                        "coppery_titi_monkey" = "Platyrrhini",
                        "crowned_lemur" = "Strepsirrhini",
                        "golden_lion_tamarin"= "Platyrrhini",
                        "silvery_marmoset" = "Platyrrhini", 
                        "emperor_tamarin" = "Platyrrhini",  
                        "white_faced_saki"  = "Platyrrhini",
                        "buff_cheek_gibbon"  = "Hominoidea",
                        "tonkean_macaque"  = "Cercopithecoidea",
                        "long_tailed_macaque"= "Cercopithecoidea",
                        "javan_langur"    = "Cercopithecoidea",  
                        "spider_monkey"   = "Platyrrhini",
                        "orangutan" = "Hominoidea",
                        ))





```

# Graphs

```{r}
subj_test <- acc_data%>%
  group_by(subject_site, species, clade)%>%
  summarise(test = ifelse(max(inter_item_interval) == 1, "pretest failed", "tested"))

subj_perf_data <- acc_data%>%
  filter(phase !="pretrain", 
         choice == "choice")%>%
  group_by(subject_site, species, clade)%>%
  summarise(perf = mean(items_accumulated))

species_perf_data <- acc_data%>%
  filter(phase !="pretrain", 
         choice == "choice")%>%
  group_by(species, clade)%>%
  tidyboot_mean(column = items_accumulated)

subj_data <- subj_test%>%
  left_join(subj_perf_data)%>%
  mutate(perf = ifelse(is.na(perf), 0,perf))

n_distinct(subj_data$species)
```

```{r}
subj_data%>%
  ggplot(aes(y = perf, x = species))+
  geom_jitter(alpha = .5, width = 0.1, height = 0, aes(pch = test))+
  facet_grid(~clade, scales = "free_x", space = "free")+
  scale_shape_manual(values = c(4,1), name = "" )+
  geom_pointrange(data = species_perf_data, aes(y = mean, ymin = ci_lower, ymax = ci_upper), col = "firebrick")+
  theme_few()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        legend.position = c(0.1, 0.8))+
  labs(x = "", y = "Mean food items accumulated")
```

```{r}
ggsave("../graphs/acc_species_overview.png", width = 12, height = 4)
```


```{r}
acc_perf_data_interval <- acc_data%>%
  filter(phase !="pretrain", 
         choice == "choice")%>%
  group_by(subject_site, site, species, clade, inter_item_interval)%>%
  summarise(perf = mean(items_accumulated))

acc_perf_data_interval_agg <- acc_data%>%
  filter(phase !="pretrain", 
         choice == "choice")%>%
  group_by(species, inter_item_interval, clade)%>%
  tidyboot_mean(column = items_accumulated)

```

```{r}
acc_perf_data_interval%>%
  arrange(clade)%>%
  ggplot(aes(y = perf, x = factor(inter_item_interval)))+
  geom_jitter(height = 0, width = 0.1, alpha = 0.25)+
  geom_pointrange(data = acc_perf_data_interval_agg, aes(y = mean, ymin = ci_lower, ymax = ci_upper, col = species))+
  geom_line(data = acc_perf_data_interval_agg, aes(y = mean, group = species, col = species))+
  facet_wrap(~species, nrow = 1)+
  scale_color_ptol(guide = "none")+
  labs(x = "Inter-item interval (seconds)", y = "Mean food items accumulated")+
  theme_few()
```

```{r}
ggsave("../graphs/acc_species_by_interval.png", width = 12, height = 4)
```

```{r}
acc_perf_site_subj <- acc_data%>%
  filter(phase !="pretrain", 
         choice == "choice",
         species == "chimpanzee")%>%
  group_by(subject_site, site, species, clade, inter_item_interval)%>%
  summarise(perf = mean(items_accumulated))

acc_perf_site <- acc_data%>%
  filter(phase !="pretrain", 
         choice == "choice",
         species == "chimpanzee")%>%
  group_by(species,site,  inter_item_interval, clade)%>%
  tidyboot_mean(column = items_accumulated)

```

```{r}
acc_perf_site_subj%>%
  arrange(clade)%>%
  ggplot(aes(y = perf, x = factor(inter_item_interval), col = site))+
  geom_jitter(height = 0, width = 0.1, alpha = 0.25)+
  geom_pointrange(data = acc_perf_site, aes(y = mean, ymin = ci_lower, ymax = ci_upper, col = site))+
  geom_line(data = acc_perf_site, aes(y = mean, group = site, col = site))+
  scale_color_colorblind(name = "Site")+
  labs(x = "Inter-item interval (seconds)", y = "Mean food items accumulated")+
  theme_few()
```

```{r}
ggsave("../graphs/acc_site.png", width = 8, height = 4)
```

